# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- alias: preview
  name: REPLACE_ME_APP_NAME
  repository: file://../REPLACE_ME_APP_NAME
